name: Go

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    -
      name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    runs-on: ubuntu-latest
    name: Create Docker 
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2

      - name: Building
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u mabels --password-stdin
          export VERSION=$(basename ${{ github.ref }})
          docker build -t zero-animal:${{ github.sha }} --build-arg VERSION=$VERSION --build-arg COMMIT=${{ github.sha }} .
          docker tag zero-animal:${{ github.sha }} ghcr.io/mabels/zero-animal:$VERSION
          docker push ghcr.io/mabels/zero-animal:$VERSION
          docker tag zero-animal:${{ github.sha }} ghcr.io/mabels/zero-animal:latest
          docker push ghcr.io/mabels/zero-animal:latest
